### ISSUE TITLE
Some DLLs/Binaries are open source or commercial?

### ISSUE THREAD

**Issue by tcsaddul** [lxuinet/Sapper#3]
I noticed that binaries like "lxui.android" are not open-source.  This will prevent commercial partners or buyers from ever touching this library due to "trust" issues. Licensing issues should be clearly stated.

**Comment by lxuinet** [comment]
Hi, after the initial publication of the library, certain conclusions were
made and an understanding of what users want to see in the final product.
Now a new version is being developed from 0, taking into account many
wishes. This will be version 2.0 and will be completely open source in the
official repository. According to the code, it will be 80-90 percent
compatible with the current library. I plan to make the product even more
productive and flexible!

пт, 9 сент. 2022 г. в 20:16, tcsaddul ***@***.***>:

**Comment by tcsaddul** [comment]
Thank you for the prompt reply.  Our company is willing to pay license fees even if it is open-source.  Or we can make donations.

**Comment by lxuinet** [comment]
Hi, thank you for your support! At the moment the product is not
commercial. In the future, I would like to have a subscription system, but
for this the product must be of the highest quality and reliable. I didn’t
even think about the donation system, but any help in the development of
the project is great!

сб, 10 сент. 2022 г. в 23:11, tcsaddul ***@***.***>:

**Comment by tcsaddul** [comment]
Well, I like the simplicity of how UIs can be built using this library. The only issue maybe is to make sure this works on iOS thru an actual demo app. Added bonus would be on how to use other UI libraries in the .NET 6.0 ecosystem especially now with .NET MAUI and its other open-source community developed libraries.
